language: php
php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

before_script:

script:
  - composer lint
  - composer stan